/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Medications-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "patients-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "doctors-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "pharmacies-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:376e2fd5-81d4-47da-ab5d-2ecec25ba88c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hHcty4ZZA",
    "aws_user_pools_web_client_id": "he20lg5ocv6udtn02f95sr5pi",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "meds",
            "endpoint": "https://phcsjyr8u4.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
